spring:
  main:
    banner-mode: off
  version: @project.version@

app:
  config-file-path: /app/config/config.yaml

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.icaroerasmo: DEBUG
